"""creating new schema with updated tables

Revision ID: 0f05309946b5
Revises:
Create Date: 2025-04-20 16:44:31.385568

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f05309946b5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athletes",
        sa.Column("athlete_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("athlete_name", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("athlete_id"),
        sa.UniqueConstraint("email"),
        schema="strava",
    )
    op.create_table(
        "activities",
        sa.Column("activity_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("athlete_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("moving_time_s", sa.Integer(), nullable=False),
        sa.Column("distance_mi", sa.Float(), nullable=False),
        sa.Column("avg_speed_ft_s", sa.Float(precision=2), nullable=False),
        sa.Column("full_datetime", sa.DateTime(), nullable=True),
        sa.Column("spm_avg", sa.Float(), nullable=True),
        sa.Column("hr_avg", sa.Float(), nullable=True),
        sa.Column("wkt_type", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("total_elev_gain_ft", sa.Float(), nullable=True),
        sa.Column("manual", sa.Boolean(), nullable=False),
        sa.Column("max_speed_ft_s", sa.Float(), nullable=True),
        sa.Column("calories", sa.Float(), nullable=True),
        sa.Column("achievement_count", sa.Integer(), nullable=True),
        sa.Column("kudos_count", sa.Integer(), nullable=True),
        sa.Column("comment_count", sa.Integer(), nullable=True),
        sa.Column("athlete_count", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("avg_power", sa.Integer(), nullable=True),
        sa.Column("sleep_rating", sa.Integer(), nullable=True),
        sa.Column("suffer_score", sa.Integer(), nullable=True),
        sa.Column("perceived_exertion", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["strava.athletes.athlete_id"],
        ),
        sa.PrimaryKeyConstraint("activity_id"),
        schema="strava",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activities", schema="strava")
    op.drop_table("athletes", schema="strava")
    # ### end Alembic commands ###
